import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StyledComponentsRegistry from './lib/registry';
import { AuthContextProvider } from "@/contexts/AuthContext";
import { ApiContext } from "@/types";
import ClientLayout from "@/components/templates/ClientLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const context: ApiContext = {
//   apiRootUrl: process.env.NEXT_PUBLIC_API_BASE_PATH || '/api/proxy',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/* <StyledComponentsRegistry>
            <AuthContextProvider context={context}>
              {children}
            </AuthContextProvider>
          </StyledComponentsRegistry> */}
          <ClientLayout>
            {children}
          </ClientLayout>
        </body>
    </html>
  );
}
