import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ShoppingCartContextProvider } from "@/contexts/ShoppingCartContext";
import ClientLayout from "@/components/templates/ClientLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/*
            ショッピングカートの状態管理プロバイダー
            アプリケーション全体でカートの状態を共有するために使用
          */}
          <ShoppingCartContextProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </ShoppingCartContextProvider>
        </body>
    </html>
  );
}
